# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: builds

on:
  push:
    # Run when main is updated
    branches: [ main, 4.x, release-4.0 ]
  pull_request:
    # Run on pull requests against main
    branches: [ main, 4.x, release-4.0 ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@main
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov ipython
        pip install -r requirements.txt
    - name: Test and generate coverage report
      # Run coverage analysis on pytest tests
      run: |
        pip install .
        py.test --cov-report=xml --cov=./
    - name: Upload coverage to Deepsource
      uses: deepsourcelabs/test-coverage-action@master
      with:
        key: python
        coverage-file: coverage.xml
        dsn: ${{ secrets.DEEPSOURCE_DSN }}
      env:
        DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
